name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile windows_source_code.py

      - name: Upload exe artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows-downloader-exe
          path: dist/windows_source_code.exe
